-- ADDENDUM.
--
-- Auth rebuild: mobile+OTP -> universal email+password, for every role.
--
-- users.email/password_hash already existed as nullable, staff-leaning
-- columns (001_users_auth.sql) — this migration promotes them to the
-- actual (NOT NULL) auth mechanism for every role instead, and removes the
-- mobile/OTP infrastructure they're replacing. Existing rows (if any) get a
-- placeholder email/blank password_hash so the NOT NULL conversion never
-- fails on data written before this migration — nothing in this app has any
-- real users yet (dev/mock gateway only), but the backfill keeps this
-- migration safe to run against any environment regardless.
--
-- operator's CHECK constraint was inline (`CHECK (...)` on the column
-- definition, no explicit `CONSTRAINT name`) — MariaDB drops an inline CHECK
-- automatically as part of dropping the column it references, so there's
-- no separate DROP CONSTRAINT step needed (confirmed empirically: MariaDB's
-- `DROP CONSTRAINT <auto-generated-name>` fails with error 1091 for this
-- kind of inline check even though information_schema reports the name
-- correctly — `DROP COLUMN` is the only reliable way to remove it).

ALTER TABLE users DROP INDEX uq_users_mobile_hash;
ALTER TABLE users DROP COLUMN mobile;
ALTER TABLE users DROP COLUMN mobile_hash;
ALTER TABLE users DROP COLUMN operator;

UPDATE users SET email = CONCAT('user-', id, '@example.invalid') WHERE email IS NULL;
UPDATE users SET password_hash = '' WHERE password_hash IS NULL;
ALTER TABLE users MODIFY COLUMN email VARCHAR(191) NOT NULL;
ALTER TABLE users MODIFY COLUMN password_hash VARCHAR(255) NOT NULL;

-- otp_requests never needs to survive this — nothing but OtpService (deleted)
-- ever read or wrote it.
DROP TABLE IF EXISTS otp_requests;

-- Password-reset tokens, same PII-lookup pattern as everything else in this
-- app (App\Core\Crypto::blindIndex()): the raw token lives only in the
-- emailed URL, never in the database — token_hash is a one-way HMAC, looked
-- up by exact match, never reversed back to the token itself.
CREATE TABLE password_reset_tokens (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    used_at    TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_password_reset_token_hash ON password_reset_tokens (token_hash);
